start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd autarky-api | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd autarky-oversight | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd battery | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd battery-provider | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd bill-api | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd client-consumption-api | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd client-database | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd client-notifier | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-adder | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-api | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-detailed | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-peak | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-provider | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-scheduler | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-verifier | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd daily-consumption-db | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd daily-production-db | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd daily-real-energy-output | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd electricity-frame | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd global-consumption-database | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd global-production-database | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd house | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd partner-api | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd producer-database | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd producers | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd production-adapter | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd production-api | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd production-provider | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd real-energy-output | npm run start:dev" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd registry-manager | npm run start:dev" &
