version: '3.8'

services:
  house:
    container_name: house
    image: house:1.0.0
    build:
      context: ./house
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    networks:
      - si5-soa
    volumes:
      - /usr/src/app
    depends_on:
      - "registry-manager"

  house-object:
    container_name: voiture
    image: house-object:1.0.0
    build:
      context: ./house-object
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3001:3001
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  scheduler:
    container_name: scheduler
    image: scheduler:1.0.0
    build:
      context: ./scheduler
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3002:3002
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  registry-manager:
    container_name: registry-manager
    image: registry-manager:1.0.0
    build:
      context: ./registry-manager
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3003:3003
    networks:
      - si5-soa
    volumes:
      - /usr/src/app


  power-grid:
    container_name: power-grid
    image: power-grid:1.0.0
    build:
      context: ./power-grid
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3004:3004
    networks:
      - si5-soa
    volumes:
      - /usr/src/app
      
  supplier:
    container_name: supplier
    image: supplier:1.0.0
    build:
      context: ./supplier
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3005:3005
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  dataservice:
    container_name: dataservice
    image: dataservice:1.0.0
    build:
      context: ./dataservice
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3006:3006
    networks:
      - si5-soa
    volumes:
      - /usr/src/app   

  consumption-verifier:
    container_name: consumption-verifier
    image: consumption-verifier:1.0.0
    build:
      context: ./consumption-verifier
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3007:3007
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  consumption-manager:
    container_name: consumption-manager
    image: consumption-manager:1.0.0
    build:
      context: ./consumption-manager
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3008:3008
    networks:
      - si5-soa
    volumes:
      - /usr/src/app
      
  scenario:
    container_name: scenario
    image: scenario:1.0.0
    build:
      context: ./scenario
      dockerfile: ./Dockerfile
    command: npm run start:prod
    networks:
      - si5-soa
    volumes:
      - /usr/src/app
    depends_on:
      - "house-object"
      - "house"
      - "supplier"
      - "power-grid"
      - "consumption-manager"
      - "scheduler"
      - "registry-manager"
      - "consumption-verifier"
      - "dataservice"

networks:
  si5-soa:
