version: '3.8'

services:

  house:
    container_name: house

    image: house:1.0.0

    build:
      context: ./house
      dockerfile: ./Dockerfile

    command: npm run start:prod

    ports:
      - 3000:3000
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  supplier:
    container_name: supplier

    image: supplier:1.0.0

    build:
      context: ./supplier
      dockerfile: ./Dockerfile

    command: npm run start:prod

    ports:
      - 3002:3000
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

networks:
  si5-soa:
