version: '3.8'

services:

  house:
    container_name: nestjs_api_prod

    image: house:1.0.0

    build:
      context: ./house
      dockerfile: ./Dockerfile

    command: npm run start:prod

    ports:
      - 3000:3000
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

networks:
  si5-soa: