version: '3.8'

services:
  house:
    container_name: house
    image: house:1.0.0
    build:
      context: ./house
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  supplier:
    container_name: supplier
    image: supplier:1.0.0
    build:
      context: ./supplier
      dockerfile: ./Dockerfile
    command: npm run start:prod
    depends_on:
      - "clock"
    ports:
      - 3002:3002
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  power-grid:
    container_name: power-grid
    image: power-grid:1.0.0
    build:
      context: ./power-grid
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3003:3003
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  clock:
    container_name: clock
    image: clock:1.0.0
    build:
      context: ./clock
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3004:3004
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

  house-object:
    container_name: voiture
    image: house-object:1.0.0
    build:
      context: ./house-object
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3005:3005
    networks:
      - si5-soa
    volumes:
      - /usr/src/app

networks:
  si5-soa:
