start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd client-database | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-adder | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-detailed | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-peak | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-provider | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-scheduler | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-verifier | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd electricity-frame | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd global-consumption-database | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd global-production-database | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd house | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd producer-database | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd producers | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd production-adapter | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd production-provider | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd registry-manager | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd client-consumption-api | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd consumption-api | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd production-api | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd bill-api | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd daily-consumption-db | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd daily-production-db | npm i" &
start powershell -command "[console]::windowwidth=100; [console]::windowheight=30; cd autarky | npm i" &