name: SI5 
on: 
  push: 
    branches: 
      - dev 
      - master 

 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      uses: actions/checkout@v2 
      name: prepare and run
      run: chmod +x ./prepare.sh
      shell: bash
      run: ./prepare.sh
      shell: bash
      id: run
      run: chmod +x ./run.sh
      shell: bash
      run: ./run.sh
      shell: bash
