name: SI5 
on: 
  push: 
    branches: 
      - dev 
      - master 

 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: prepare and run
      - run: |
            chmod +x ./prepare.sh
            ./prepare.sh
        shell: bash
      - run: |
            chmod +x ./run.sh
            ./run.sh
        shell: bash
